### ISSUE TITLE
 Crash when user inserts other format of date 

### ISSUE THREAD

**Issue by Anna-Petko** [Anna-Petko/todo_list#10]
Exception in thread "main" java.time.format.DateTimeParseException: Text '11-11-2019' could not be parsed at index 2
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.base/java.time.LocalDate.parse(LocalDate.java:428)
	at com.company.UserInput.insertDataForTask(UserInput.java:23)
	at com.company.Menu.chooseCommand(Menu.java:44)
	at com.company.Main.main(Main.java:8)

**Comment by Anna-Petko** [comment]
#12
